name: Publish Release
on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"
env:
  VERSION: 2.5.0

jobs:
  # pypi:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Build pypi package
  #       run: echo "Building package on release"
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - run: python setup.py sdist --formats=gztar
  #     - name: Publish package
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         password: ${{ secrets.PYPI_API_TOKEN }}

  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/opencravat:${{ github.sha }}
  mac:
    runs-on: macos-14
    env:
      MINICONDA_DIST: Miniconda3-py311_24.1.2-0-MacOSX-x86_64
    steps:
      - name: Install build tools
        run: |
          brew install --cask platypus
          gunzip  /Applications/Platypus.app/Contents/Resources/platypus_clt.gz
          curl -o miniconda.sh https://repo.anaconda.com/miniconda/${MINICONDA_DIST}.sh
          chmod +x miniconda.sh
          ./miniconda.sh -b -p ./miniconda -u
      - name: Setup build environment
        run: |
          miniconda/bin/conda init bash
          . ~/.bash_profile
          conda create -y -n py3 python=3.11 pip
          pwd
